version: '3.9'

services:
  web:
    container_name: ott_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      DB_NAME: default
      DB_USER: mysql
      DB_PASSWORD: fP5OgBVmT3MDPQthaUddpinFnE4QM4WkcsuPKeUt2b2eyAYN9Omh4osqZJLleXoj
      DB_HOST: v0s0408k4gsos8w0os4kwo80
      DB_PORT: 3306

  phpmyadmin:
    container_name: ott_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: v0s0408k4gsos8w0os4kwo80
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: fP5OgBVmT3MDPQthaUddpinFnE4QM4WkcsuPKeUt2b2eyAYN9Omh4osqZJLleXoj

volumes:
  static_volume:
  media_volume:
