version: '3.9'

services:
  web:
    container_name: ott_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      DB_NAME: ottdata
      DB_USER: root
      DB_PASSWORD: fP5OgBVmT3MDPQthaUddpinFnE4QM4WkcsuPKeUt2b2eyAYN9Omh4osqZJLleXoj
      DB_HOST: db  # Internal Docker service name for MySQL
      DB_PORT: 3306
    depends_on:
      - db

  db:
    container_name: ott_mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ottdata
      MYSQL_ROOT_PASSWORD: fP5OgBVmT3MDPQthaUddpinFnE4QM4WkcsuPKeUt2b2eyAYN9Omh4osqZJLleXoj
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    container_name: ott_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"  # Changed from 8080 to avoid port conflict
    environment:
      PMA_HOST: db  # Internal Docker service name, not external domain
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: fP5OgBVmT3MDPQthaUddpinFnE4QM4WkcsuPKeUt2b2eyAYN9Omh4osqZJLleXoj
      PMA_ABSOLUTE_URI: https://db.ottplatform.shijin.in  # External URL to access phpMyAdmin
    depends_on:
      - db

volumes:
  dbdata:
  static_volume:
  media_volume:
